package com.pse.thinder.backend.repositories;

import com.pse.thinder.backend.databaseFeatures.Degree;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.UUID;

/**
 * 
 * Repository to access the Degree table of the database
 *
 */
public interface DegreeRepository extends JpaRepository<Degree, UUID> {

	/**
	 * Autogenerated method to find all degrees of the university with the given id
	 * @param universityId the university id
	 * @return the list of degrees
	 */
    List<Degree> findByUniversityId(UUID universityId);
}
