package com.pse.thinder.backend.repositories;

import com.pse.thinder.backend.databaseFeatures.token.PasswordResetToken;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;
import java.util.UUID;

/**
 * 
 * Repository to access the PasswordResetToken table of the database
 *
 */
public interface PasswordResetTokenRepository extends JpaRepository<PasswordResetToken, UUID> {

	/**
	 * Autogenerated method to find the PasswordResetToken belonging to a token if one exists
	 * @param token the identifier for the PasswordResetToken
	 * @return the optional for the PasswordResetToken
	 */
    Optional<PasswordResetToken> findByToken(String token);
}
