package com.pse.thinder.backend.repositories;

import java.util.ArrayList;
import java.util.UUID;

import com.pse.thinder.backend.databaseFeatures.thesis.Thesis;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * 
 * Repository to access the Thesis table of the database
 *
 */
public interface ThesisRepository extends JpaRepository<Thesis, UUID>{

	/**
	 * Autogenerated method to find all theses belonging to the supervisor with the given id
	 * 
	 * @param supervisorId the supervisor id
	 * @return the list of theses
	 */
    ArrayList<Thesis> findBySupervisorId(UUID supervisorId);
}
