package com.pse.thinder.backend.repositories;

import com.pse.thinder.backend.databaseFeatures.University;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;
import java.util.UUID;

/**
 * 
 * Repository to access the University table of the database
 *
 */
public interface UniversityRepository extends JpaRepository<University, UUID> {
	/**
	 * Autogenerated method to find a university with the given name if one exists
	 * @param name the name to search
	 * @return the optional for university
	 */
    public Optional<University> findByName(String name);
}
