package com.pse.thinder.backend.repositories;

import com.pse.thinder.backend.databaseFeatures.token.VerificationToken;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * 
 * Repository to access the VerificationToken table of the database
 *
 */
@Repository
public interface VerificationTokenRepository  extends JpaRepository<VerificationToken, UUID> {

	/**
	 * Autogenerated method to find the VerificationToken belonging to a token if one exists
	 * @param token the identifier for the VerificationToken
	 * @return the optional for the VerificationToken
	 */
    Optional<VerificationToken> findByToken(String token);
}
